# 
# Create new networks on OpenShift
---
- hosts: localhost
  vars:
    net_dict:    
      net-ngap: 192.168.5.0/24
      net-gtp: 192.168.6.0/24
      net-pfcp: 192.168.7.0/24
      net-ran: 192.168.8.0/24
    spec_string: |-
        {
            "cniVersion": "0.3.1",
            "name": "{{ item.key }}",
            "type": "macvlan",
            "master": "{{ openshift.host_ifname }}",
            "mode": "bridge",
            "ipam": {
              "type": "host-local",
              "subnet": "{{ item.value }}"
            }
        }

  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create additional networks on OpenShift
    k8s:
      state: present
      apply: yes
      host: "{{ openshift.api_url }}" 
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: "k8s.cni.cncf.io/v1"
        kind: NetworkAttachmentDefinition
        metadata:
          name: "{{ item.key }}"
          namespace: 5gcore
        spec:
          config: "{{ spec_string | to_json }}"
    loop: "{{ net_dict | dict2items }}"
